=== miranvodnik/xdbd/xdbd-xsd/system.columns.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="system.columns_root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="system.columns" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="column_id"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="column_name"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="128"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="table_id"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="data_type"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="type_name"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="128"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="column_size"  minOccurs="0" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="buffer_length"  minOccurs="0" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="decimal_digits"  minOccurs="0" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="num_prec_radix"  minOccurs="0" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="nullable"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="remarks"  minOccurs="0" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="128"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="column_def"  minOccurs="0" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="128"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="date_time_code"  minOccurs="0" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="char_octet_length"  minOccurs="0" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ordinal_position"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="is_nullable"  minOccurs="0" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="254"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					<xs:key name="XPKsystem.columns">
						<xs:selector xpath=".//system.columns"/>
						<xs:field xpath="column_id"/>
					</xs:key>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== miranvodnik/xdbd/xdbd-xml/system.columns.xml
<?xml version="1.0" encoding="UTF-8"?>
<system.columns_root xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='system.columns.xsd'>
  <system.columns>
    <column_id>1</column_id>
    <column_name>nodeid</column_name>
    <table_id>1</table_id>
    <data_type>4</data_type>
    <type_name>SQLINTEGER</type_name>
    <column_size>4</column_size>
    <nullable>0</nullable>
    <ordinal_position>1</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>2</column_id>
    <column_name>filter_id</column_name>
    <table_id>1</table_id>
    <data_type>5</data_type>
    <type_name>SQLSMALLINT</type_name>
    <column_size>2</column_size>
    <nullable>0</nullable>
    <ordinal_position>2</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>3</column_id>
    <column_name>basic_filt_order</column_name>
    <table_id>1</table_id>
    <data_type>5</data_type>
    <type_name>SQLSMALLINT</type_name>
    <column_size>2</column_size>
    <nullable>0</nullable>
    <ordinal_position>3</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>4</column_id>
    <column_name>basic_filt_action</column_name>
    <table_id>1</table_id>
    <data_type>5</data_type>
    <type_name>SQLSMALLINT</type_name>
    <column_size>2</column_size>
    <nullable>0</nullable>
    <ordinal_position>4</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>5</column_id>
    <column_name>src_mac_addr</column_name>
    <table_id>1</table_id>
    <data_type>12</data_type>
    <type_name>SQLVARCHAR</type_name>
    <column_size>17</column_size>
    <nullable>1</nullable>
    <ordinal_position>5</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>6</column_id>
    <column_name>dst_mac_addr</column_name>
    <table_id>1</table_id>
    <data_type>12</data_type>
    <type_name>SQLVARCHAR</type_name>
    <column_size>17</column_size>
    <nullable>1</nullable>
    <ordinal_position>6</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>7</column_id>
    <column_name>ll_prot</column_name>
    <table_id>1</table_id>
    <data_type>4</data_type>
    <type_name>SQLINTEGER</type_name>
    <column_size>4</column_size>
    <nullable>1</nullable>
    <ordinal_position>7</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>8</column_id>
    <column_name>src_ip_addr</column_name>
    <table_id>1</table_id>
    <data_type>12</data_type>
    <type_name>SQLVARCHAR</type_name>
    <column_size>15</column_size>
    <nullable>1</nullable>
    <ordinal_position>8</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>9</column_id>
    <column_name>src_ip_mask</column_name>
    <table_id>1</table_id>
    <data_type>12</data_type>
    <type_name>SQLVARCHAR</type_name>
    <column_size>15</column_size>
    <nullable>1</nullable>
    <ordinal_position>9</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>10</column_id>
    <column_name>dst_ip_addr</column_name>
    <table_id>1</table_id>
    <data_type>12</data_type>
    <type_name>SQLVARCHAR</type_name>
    <column_size>15</column_size>
    <nullable>1</nullable>
    <ordinal_position>10</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>11</column_id>
    <column_name>dst_ip_mask</column_name>
    <table_id>1</table_id>
    <data_type>12</data_type>
    <type_name>SQLVARCHAR</type_name>
    <column_size>15</column_size>
    <nullable>1</nullable>
    <ordinal_position>11</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>12</column_id>
    <column_name>ip_prot</column_name>
    <table_id>1</table_id>
    <data_type>5</data_type>
    <type_name>SQLSMALLINT</type_name>
    <column_size>2</column_size>
    <nullable>1</nullable>
    <ordinal_position>12</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>13</column_id>
    <column_name>src_porthigh</column_name>
    <table_id>1</table_id>
    <data_type>4</data_type>
    <type_name>SQLINTEGER</type_name>
    <column_size>4</column_size>
    <nullable>1</nullable>
    <ordinal_position>13</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>14</column_id>
    <column_name>src_portlow</column_name>
    <table_id>1</table_id>
    <data_type>4</data_type>
    <type_name>SQLINTEGER</type_name>
    <column_size>4</column_size>
    <nullable>1</nullable>
    <ordinal_position>14</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>15</column_id>
    <column_name>dst_porthigh</column_name>
    <table_id>1</table_id>
    <data_type>4</data_type>
    <type_name>SQLINTEGER</type_name>
    <column_size>4</column_size>
    <nullable>1</nullable>
    <ordinal_position>15</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>16</column_id>
    <column_name>dst_portlow</column_name>
    <table_id>1</table_id>
    <data_type>4</data_type>
    <type_name>SQLINTEGER</type_name>
    <column_size>4</column_size>
    <nullable>1</nullable>
    <ordinal_position>16</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>17</column_id>
    <column_name>icmp_type</column_name>
    <table_id>1</table_id>
    <data_type>5</data_type>
    <type_name>SQLSMALLINT</type_name>
    <column_size>2</column_size>
    <nullable>1</nullable>
    <ordinal_position>17</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>18</column_id>
    <column_name>tos</column_name>
    <table_id>1</table_id>
    <data_type>5</data_type>
    <type_name>SQLSMALLINT</type_name>
    <column_size>2</column_size>
    <nullable>1</nullable>
    <ordinal_position>18</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>19</column_id>
    <column_name>precedense</column_name>
    <table_id>1</table_id>
    <data_type>5</data_type>
    <type_name>SQLSMALLINT</type_name>
    <column_size>2</column_size>
    <nullable>1</nullable>
    <ordinal_position>19</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>20</column_id>
    <column_name>nodeid</column_name>
    <table_id>2</table_id>
    <data_type>4</data_type>
    <type_name>SQLINTEGER</type_name>
    <column_size>4</column_size>
    <nullable>0</nullable>
    <ordinal_position>20</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>21</column_id>
    <column_name>regsigtype</column_name>
    <table_id>2</table_id>
    <data_type>5</data_type>
    <type_name>SQLSMALLINT</type_name>
    <column_size>2</column_size>
    <nullable>0</nullable>
    <ordinal_position>21</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>22</column_id>
    <column_name>regsigvariant</column_name>
    <table_id>2</table_id>
    <data_type>5</data_type>
    <type_name>SQLSMALLINT</type_name>
    <column_size>2</column_size>
    <nullable>0</nullable>
    <ordinal_position>22</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>23</column_id>
    <column_name>cas_attenuation</column_name>
    <table_id>2</table_id>
    <data_type>4</data_type>
    <type_name>SQLINTEGER</type_name>
    <column_size>4</column_size>
    <nullable>0</nullable>
    <ordinal_position>23</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>24</column_id>
    <column_name>wait_su</column_name>
    <table_id>2</table_id>
    <data_type>4</data_type>
    <type_name>SQLINTEGER</type_name>
    <column_size>4</column_size>
    <nullable>0</nullable>
    <ordinal_position>24</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>25</column_id>
    <column_name>delay_before_end</column_name>
    <table_id>2</table_id>
    <data_type>4</data_type>
    <type_name>SQLINTEGER</type_name>
    <column_size>4</column_size>
    <nullable>0</nullable>
    <ordinal_position>25</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>26</column_id>
    <column_name>pulse_length</column_name>
    <table_id>2</table_id>
    <data_type>4</data_type>
    <type_name>SQLINTEGER</type_name>
    <column_size>4</column_size>
    <nullable>0</nullable>
    <ordinal_position>26</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>27</column_id>
    <column_name>pulse_long</column_name>
    <table_id>2</table_id>
    <data_type>4</data_type>
    <type_name>SQLINTEGER</type_name>
    <column_size>4</column_size>
    <nullable>0</nullable>
    <ordinal_position>27</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>28</column_id>
    <column_name>pulse_secure</column_name>
    <table_id>2</table_id>
    <data_type>4</data_type>
    <type_name>SQLINTEGER</type_name>
    <column_size>4</column_size>
    <nullable>0</nullable>
    <ordinal_position>28</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>29</column_id>
    <column_name>pause_length</column_name>
    <table_id>2</table_id>
    <data_type>4</data_type>
    <type_name>SQLINTEGER</type_name>
    <column_size>4</column_size>
    <nullable>0</nullable>
    <ordinal_position>29</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>30</column_id>
    <column_name>pause_long</column_name>
    <table_id>2</table_id>
    <data_type>4</data_type>
    <type_name>SQLINTEGER</type_name>
    <column_size>4</column_size>
    <nullable>0</nullable>
    <ordinal_position>30</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>31</column_id>
    <column_name>pause_secure</column_name>
    <table_id>2</table_id>
    <data_type>4</data_type>
    <type_name>SQLINTEGER</type_name>
    <column_size>4</column_size>
    <nullable>0</nullable>
    <ordinal_position>31</ordinal_position>
  </system.columns>
  <system.columns>
    <column_id>32</column_id>
    <column_name>regsigparvalue1</column_name>
    <table_id>2</table_id>
    <data_type>4</data_type>
    <type_name>SQLINTEGER</type_name>
    <column_size>4</column_size>
