=== miranvodnik/xdbd/xdbd-xsd/xdbd_trigger.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="xdbd_trigger_root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="xdbd_trigger" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="trigger_id"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
										<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="trigger_name"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
										<xs:restriction base = "xs:string">
											<xs:minLength value="0"/>
											<xs:maxLength value="64"/>
										</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="trigger_library"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
										<xs:restriction base = "xs:string">
											<xs:minLength value="0"/>
											<xs:maxLength value="64"/>
										</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="trigger_load"  minOccurs="0" maxOccurs="1">
								<xs:simpleType>
										<xs:restriction base = "xs:string">
											<xs:minLength value="0"/>
											<xs:maxLength value="64"/>
										</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="trigger_fire"  minOccurs="0" maxOccurs="1">
								<xs:simpleType>
										<xs:restriction base = "xs:string">
											<xs:minLength value="0"/>
											<xs:maxLength value="64"/>
										</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="trigger_unload"  minOccurs="0" maxOccurs="1">
								<xs:simpleType>
										<xs:restriction base = "xs:string">
											<xs:minLength value="0"/>
											<xs:maxLength value="64"/>
										</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="trigger_table"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
										<xs:restriction base = "xs:string">
											<xs:minLength value="0"/>
											<xs:maxLength value="64"/>
										</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="trigger_function"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
										<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="xdbd_trigger_par" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="trigger_par_id"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
										<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="trigger_id"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
										<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="trigger_par_name"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
										<xs:restriction base = "xs:string">
											<xs:minLength value="0"/>
											<xs:maxLength value="64"/>
										</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="trigger_par_value"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
										<xs:restriction base = "xs:string">
											<xs:minLength value="0"/>
											<xs:maxLength value="64"/>
										</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== miranvodnik/xdbd/sdl-triggers.xml
<?xml version="1.0" encoding="UTF-8"?>
<xdbd_trigger_root
 xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
 xsi:noNamespaceSchemaLocation='xdbd_trigger.xsd'>
 <xdbd_trigger>
  <trigger_id>1</trigger_id>
  <trigger_name>trigger_h248_nonstd_prf</trigger_name>
  <trigger_library>libxdbdsdltrigger.so</trigger_library>
  <trigger_load>nmFunc_h248_nonstd_prf_load</trigger_load>
  <trigger_fire>nmFunc_h248_nonstd_prf_fire</trigger_fire>
  <trigger_unload>nmFunc_h248_nonstd_prf_unload</trigger_unload>
  <trigger_table>h248_nonstd_prf</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>2</trigger_id>
  <trigger_name>trigger_stat_adapter</trigger_name>
  <trigger_library>libxdbdsdltrigger.so</trigger_library>
  <trigger_load>nmFunc_stat_adapter_load</trigger_load>
  <trigger_fire>nmFunc_stat_adapter_fire</trigger_fire>
  <trigger_unload>nmFunc_stat_adapter_unload</trigger_unload>
  <trigger_table>stat_adapter</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>3</trigger_id>
  <trigger_name>trigger_h248_intf_profile</trigger_name>
  <trigger_library>libxdbdsdltrigger.so</trigger_library>
  <trigger_load>nmFunc_h248_intf_profile_load</trigger_load>
  <trigger_fire>nmFunc_h248_intf_profile_fire</trigger_fire>
  <trigger_unload>nmFunc_h248_intf_profile_unload</trigger_unload>
  <trigger_table>h248_intf_profile</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>4</trigger_id>
  <trigger_name>trigger_vxml_config</trigger_name>
  <trigger_library>libxdbdsdltrigger.so</trigger_library>
  <trigger_load>nmFunc_vxml_config_load</trigger_load>
  <trigger_fire>nmFunc_vxml_config_fire</trigger_fire>
  <trigger_unload>nmFunc_vxml_config_unload</trigger_unload>
  <trigger_table>vxml_config</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>5</trigger_id>
  <trigger_name>trigger_vxml_server</trigger_name>
  <trigger_library>libxdbdsdltrigger.so</trigger_library>
  <trigger_load>nmFunc_vxml_server_load</trigger_load>
  <trigger_fire>nmFunc_vxml_server_fire</trigger_fire>
  <trigger_unload>nmFunc_vxml_server_unload</trigger_unload>
  <trigger_table>vxml_server</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>6</trigger_id>
  <trigger_name>trigger_vxml_trace</trigger_name>
  <trigger_library>libxdbdsdltrigger.so</trigger_library>
  <trigger_load>nmFunc_vxml_trace_load</trigger_load>
  <trigger_fire>nmFunc_vxml_trace_fire</trigger_fire>
  <trigger_unload>nmFunc_vxml_trace_unload</trigger_unload>
  <trigger_table>vxml_trace</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>7</trigger_id>
  <trigger_name>trigger_sys_interface</trigger_name>
  <trigger_library>libxdbdsdltrigger.so</trigger_library>
  <trigger_load>nmFunc_sys_interface_load</trigger_load>
  <trigger_fire>nmFunc_sys_interface_fire</trigger_fire>
  <trigger_unload>nmFunc_sys_interface_unload</trigger_unload>
  <trigger_table>sys_interface</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>8</trigger_id>
  <trigger_name>trigger_statistics_group</trigger_name>
  <trigger_library>libxdbdsdltrigger.so</trigger_library>
  <trigger_load>nmFunc_statistics_group_load</trigger_load>
  <trigger_fire>nmFunc_statistics_group_fire</trigger_fire>
  <trigger_unload>nmFunc_statistics_group_unload</trigger_unload>
  <trigger_table>statistics_group</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
</xdbd_trigger_root>

=== miranvodnik/xdbd/nmgen-sdl/sdl-triggers.xml
<?xml version="1.0" encoding="UTF-8"?>
<xdbd_trigger_root
 xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
 xsi:noNamespaceSchemaLocation='xdbd_trigger.xsd'>
 <xdbd_trigger>
  <trigger_id>1</trigger_id>
  <trigger_name>trigger_h248_nonstd_prf</trigger_name>
  <trigger_library>libxdbdsdltrigger.so</trigger_library>
  <trigger_load>nmFunc_h248_nonstd_prf_load</trigger_load>
  <trigger_fire>nmFunc_h248_nonstd_prf_fire</trigger_fire>
  <trigger_unload>nmFunc_h248_nonstd_prf_unload</trigger_unload>
  <trigger_table>h248_nonstd_prf</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>2</trigger_id>
  <trigger_name>trigger_vxml_config</trigger_name>
  <trigger_library>libxdbdsdltrigger.so</trigger_library>
  <trigger_load>nmFunc_vxml_config_load</trigger_load>
  <trigger_fire>nmFunc_vxml_config_fire</trigger_fire>
  <trigger_unload>nmFunc_vxml_config_unload</trigger_unload>
  <trigger_table>vxml_config</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>3</trigger_id>
  <trigger_name>trigger_vxml_server</trigger_name>
  <trigger_library>libxdbdsdltrigger.so</trigger_library>
  <trigger_load>nmFunc_vxml_server_load</trigger_load>
  <trigger_fire>nmFunc_vxml_server_fire</trigger_fire>
  <trigger_unload>nmFunc_vxml_server_unload</trigger_unload>
  <trigger_table>vxml_server</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>5</trigger_id>
  <trigger_name>trigger_vxml_trace</trigger_name>
  <trigger_library>libxdbdsdltrigger.so</trigger_library>
  <trigger_load>nmFunc_vxml_trace_load</trigger_load>
  <trigger_fire>nmFunc_vxml_trace_fire</trigger_fire>
  <trigger_unload>nmFunc_vxml_trace_unload</trigger_unload>
  <trigger_table>vxml_trace</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>6</trigger_id>
  <trigger_name>trigger_sys_interface</trigger_name>
  <trigger_library>libxdbdsdltrigger.so</trigger_library>
  <trigger_load>nmFunc_sys_interface_load</trigger_load>
  <trigger_fire>nmFunc_sys_interface_fire</trigger_fire>
  <trigger_unload>nmFunc_sys_interface_unload</trigger_unload>
  <trigger_table>sys_interface</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
</xdbd_trigger_root>

=== miranvodnik/xdbd/xml-db/xml-db-old/mqtrigger.xml
<?xml version="1.0" encoding="UTF-8"?>
<xdbd_trigger_root
 xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
 xsi:noNamespaceSchemaLocation='xdbd_trigger.xsd'>
 <xdbd_trigger>
  <trigger_id>1</trigger_id>
  <trigger_name>trigger_syslog_client</trigger_name>
  <trigger_library>libxdbdmqtrigger.so</trigger_library>
  <trigger_load>nmFunc_syslog_client_load</trigger_load>
  <trigger_fire>nmFunc_syslog_client_fire</trigger_fire>
  <trigger_unload>nmFunc_syslog_client_unload</trigger_unload>
  <trigger_table>syslog_client</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>2</trigger_id>
  <trigger_name>trigger_filter</trigger_name>
  <trigger_library>libxdbdmqtrigger.so</trigger_library>
  <trigger_load>nmFunc_filter_load</trigger_load>
  <trigger_fire>nmFunc_filter_fire</trigger_fire>
  <trigger_unload>nmFunc_filter_unload</trigger_unload>
  <trigger_table>filter</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>3</trigger_id>
  <trigger_name>trigger_basic_filter</trigger_name>
  <trigger_library>libxdbdmqtrigger.so</trigger_library>
  <trigger_load>nmFunc_basic_filter_load</trigger_load>
  <trigger_fire>nmFunc_basic_filter_fire</trigger_fire>
  <trigger_unload>nmFunc_basic_filter_unload</trigger_unload>
  <trigger_table>basic_filter</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>4</trigger_id>
  <trigger_name>trigger_ip_route</trigger_name>
  <trigger_library>libxdbdmqtrigger.so</trigger_library>
  <trigger_load>nmFunc_ip_route_load</trigger_load>
  <trigger_fire>nmFunc_ip_route_fire</trigger_fire>
  <trigger_unload>nmFunc_ip_route_unload</trigger_unload>
  <trigger_table>ip_route</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>5</trigger_id>
  <trigger_name>trigger_error_filter</trigger_name>
  <trigger_library>libxdbdmqtrigger.so</trigger_library>
  <trigger_load>nmFunc_error_filter_load</trigger_load>
  <trigger_fire>nmFunc_error_filter_fire</trigger_fire>
  <trigger_unload>nmFunc_error_filter_unload</trigger_unload>
  <trigger_table>error_filter</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>6</trigger_id>
  <trigger_name>trigger_filter_grp_member</trigger_name>
  <trigger_library>libxdbdmqtrigger.so</trigger_library>
  <trigger_load>nmFunc_filter_grp_member_load</trigger_load>
  <trigger_fire>nmFunc_filter_grp_member_fire</trigger_fire>
  <trigger_unload>nmFunc_filter_grp_member_unload</trigger_unload>
  <trigger_table>filter_grp_member</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>7</trigger_id>
  <trigger_name>trigger_test_program</trigger_name>
  <trigger_library>libxdbdmqtrigger.so</trigger_library>
  <trigger_load>nmFunc_test_program_load</trigger_load>
  <trigger_fire>nmFunc_test_program_fire</trigger_fire>
  <trigger_unload>nmFunc_test_program_unload</trigger_unload>
  <trigger_table>test_program</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>8</trigger_id>
  <trigger_name>trigger_eth_interface</trigger_name>
  <trigger_library>libxdbdmqtrigger.so</trigger_library>
  <trigger_load>nmFunc_eth_interface_load</trigger_load>
  <trigger_fire>nmFunc_eth_interface_fire</trigger_fire>
  <trigger_unload>nmFunc_eth_interface_unload</trigger_unload>
  <trigger_table>eth_interface</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
 <xdbd_trigger>
  <trigger_id>9</trigger_id>
  <trigger_name>trigger_ip_device</trigger_name>
  <trigger_library>libxdbdmqtrigger.so</trigger_library>
  <trigger_load>nmFunc_ip_device_load</trigger_load>
  <trigger_fire>nmFunc_ip_device_fire</trigger_fire>
  <trigger_unload>nmFunc_ip_device_unload</trigger_unload>
  <trigger_table>ip_device</trigger_table>
  <trigger_function>14</trigger_function>
 </xdbd_trigger>
</xdbd_trigger_root>
