=== miranvodnik/xdbd/system.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="system_root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="disk_usage" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nodeid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="file_system_id"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="file_system_name"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:string">
											<xs:minLength value="0"/>
											<xs:maxLength value="50"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="disk_size"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="free_space_low" default="10" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="free_space_low_min" default="1" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="free_space_low_max" default="50" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="free_space_crit" default="5" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="free_space_mincrit" default="1" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="free_space_maxcrit" default="20" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="free_space_current"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							</xs:sequence>
					</xs:complexType>
				</xs:element>
			<xs:element name="error_priority" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nodeid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="errpri_id"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="errcod"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="errpri"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="obj_mask"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:string">
											<xs:minLength value="0"/>
											<xs:maxLength value="80"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							</xs:sequence>
					</xs:complexType>
				</xs:element>
			<xs:element name="test_error" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nodeid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="errcod"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="errpri"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="errtype"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="measure"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="measure_act"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="prob_cause"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="measure_lib"  minOccurs="0" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:string">
											<xs:minLength value="0"/>
											<xs:maxLength value="20"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="measure_func"  minOccurs="0" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:string">
											<xs:minLength value="0"/>
											<xs:maxLength value="20"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="XPKdisk_usage">
			<xs:selector xpath=".//disk_usage"/>
			<xs:field xpath="nodeid"/>
			<xs:field xpath="file_system_id"/>
			</xs:key>
		<xs:key name="XPKerror_priority">
			<xs:selector xpath=".//error_priority"/>
			<xs:field xpath="nodeid"/>
			<xs:field xpath="errpri_id"/>
			</xs:key>
		<xs:key name="XPKtest_error">
			<xs:selector xpath=".//test_error"/>
			<xs:field xpath="nodeid"/>
			<xs:field xpath="errcod"/>
			</xs:key>
		<xs:unique name="XAK1disk_usage">
			<xs:selector xpath=".//disk_usage"/>
			<xs:field xpath="nodeid"/>
			<xs:field xpath="file_system_name"/>
			</xs:unique>
		
		
		<xs:keyref name="XIF1error_priority"  refer="XPKtest_error">
			<xs:selector xpath=".//error_priority"/>
			<xs:field xpath="nodeid"/>
			<xs:field xpath="errcod"/>
			</xs:keyref>
		
	</xs:element>
</xs:schema>

=== miranvodnik/xdbd/xml-db/xml-db/system.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<system_root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='system.xsd'>

     <disk_usage>
      <nodeid>2000</nodeid>
      <file_system_id>1</file_system_id>
      <file_system_name>/</file_system_name>
      <disk_size>0</disk_size>
      <free_space_low>10</free_space_low>
      <free_space_low_min>10</free_space_low_min>
      <free_space_low_max>50</free_space_low_max>
      <free_space_crit>3</free_space_crit>
      <free_space_mincrit>1</free_space_mincrit>
      <free_space_maxcrit>10</free_space_maxcrit>
      <free_space_current>0</free_space_current>
     </disk_usage>
      <disk_usage>
      <nodeid>2000</nodeid>
      <file_system_id>2</file_system_id>
      <file_system_name>/opt</file_system_name>
      <disk_size>0</disk_size>
      <free_space_low>20</free_space_low>
      <free_space_low_min>10</free_space_low_min>
      <free_space_low_max>50</free_space_low_max>
      <free_space_crit>10</free_space_crit>
      <free_space_mincrit>1</free_space_mincrit>
      <free_space_maxcrit>10</free_space_maxcrit>
      <free_space_current>0</free_space_current>
     </disk_usage>
      <disk_usage>
      <nodeid>2000</nodeid>
      <file_system_id>3</file_system_id>
      <file_system_name>/opt/si2000/mnroot</file_system_name>
      <disk_size>0</disk_size>
      <free_space_low>10</free_space_low>
      <free_space_low_min>10</free_space_low_min>
      <free_space_low_max>50</free_space_low_max>
      <free_space_crit>3</free_space_crit>
      <free_space_mincrit>1</free_space_mincrit>
      <free_space_maxcrit>10</free_space_maxcrit>
      <free_space_current>0</free_space_current>
     </disk_usage>
      <disk_usage>
      <nodeid>2000</nodeid>
      <file_system_id>4</file_system_id>
      <file_system_name>/opt/si2000/neroot/files</file_system_name>
      <disk_size>0</disk_size>
      <free_space_low>10</free_space_low>
      <free_space_low_min>10</free_space_low_min>
      <free_space_low_max>50</free_space_low_max>
      <free_space_crit>3</free_space_crit>
      <free_space_mincrit>1</free_space_mincrit>
      <free_space_maxcrit>10</free_space_maxcrit>
      <free_space_current>0</free_space_current>
     </disk_usage>
      <disk_usage>
      <nodeid>2000</nodeid>
      <file_system_id>5</file_system_id>
      <file_system_name>/var/volatile/log</file_system_name>
      <disk_size>0</disk_size>
      <free_space_low>10</free_space_low>
      <free_space_low_min>10</free_space_low_min>
      <free_space_low_max>50</free_space_low_max>
      <free_space_crit>5</free_space_crit>
      <free_space_mincrit>1</free_space_mincrit>
      <free_space_maxcrit>10</free_space_maxcrit>
      <free_space_current>0</free_space_current>
     </disk_usage>
      <disk_usage>
      <nodeid>2000</nodeid>
      <file_system_id>6</file_system_id>
      <file_system_name>/opt/si2000/neroot/vxml</file_system_name>
      <disk_size>0</disk_size>
      <free_space_low>10</free_space_low>
      <free_space_low_min>10</free_space_low_min>
      <free_space_low_max>50</free_space_low_max>
      <free_space_crit>3</free_space_crit>
      <free_space_mincrit>1</free_space_mincrit>
      <free_space_maxcrit>10</free_space_maxcrit>
      <free_space_current>0</free_space_current>
     </disk_usage>

     <test_error>
      <nodeid>2000</nodeid>
      <errcod>100010</errcod>
      <errpri>4</errpri>
      <errtype>5</errtype>
      <measure>31</measure>
      <measure_act>1</measure_act>
      <prob_cause>59</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>100170</errcod>
      <errpri>1</errpri>
      <errtype>4</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>158</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>100200</errcod>
      <errpri>4</errpri>
      <errtype>4</errtype>
      <measure>2</measure>
      <measure_act>1</measure_act>
      <prob_cause>158</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>100210</errcod>
      <errpri>4</errpri>
      <errtype>4</errtype>
      <measure>2</measure>
      <measure_act>1</measure_act>
      <prob_cause>158</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>100220</errcod>
      <errpri>4</errpri>
      <errtype>4</errtype>
      <measure>2</measure>
      <measure_act>1</measure_act>
      <prob_cause>158</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>300230</errcod>
      <errpri>4</errpri>
      <errtype>1</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>26</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>300240</errcod>
      <errpri>4</errpri>
      <errtype>1</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>1024</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>500050</errcod>
      <errpri>3</errpri>
      <errtype>4</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>156</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>600010</errcod>
      <errpri>2</errpri>
      <errtype>4</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>151</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>600020</errcod>
      <errpri>1</errpri>
      <errtype>4</errtype>
      <measure>113</measure>
      <measure_act>1</measure_act>
      <prob_cause>151</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>600030</errcod>
      <errpri>2</errpri>
      <errtype>4</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>161</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>600280</errcod>
      <errpri>2</errpri>
      <errtype>4</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>151</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>600130</errcod>
      <errpri>1</errpri>
      <errtype>5</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>73</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>600290</errcod>
      <errpri>1</errpri>
      <errtype>4</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>151</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>700050</errcod>
      <errpri>1</errpri>
      <errtype>5</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>69</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>700060</errcod>
      <errpri>3</errpri>
      <errtype>5</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>151</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>700070</errcod>
      <errpri>1</errpri>
      <errtype>5</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>151</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>700080</errcod>
      <errpri>1</errpri>
      <errtype>4</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>202</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>800110</errcod>
      <errpri>2</errpri>
      <errtype>4</errtype>
      <measure>104</measure>
      <measure_act>1</measure_act>
      <prob_cause>156</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>1300010</errcod>
      <errpri>1</errpri>
      <errtype>5</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>70</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>1300030</errcod>
      <errpri>1</errpri>
      <errtype>5</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>70</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>1300040</errcod>
      <errpri>1</errpri>
      <errtype>5</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>163</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>1300060</errcod>
      <errpri>2</errpri>
      <errtype>5</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>70</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>1700250</errcod>
      <errpri>3</errpri>
      <errtype>4</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>532</prob_cause>
     </test_error>
    <test_error>
      <nodeid>2000</nodeid>
      <errcod>1700260</errcod>
      <errpri>1</errpri>
      <errtype>2</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>10</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>1700280</errcod>
      <errpri>4</errpri>
      <errtype>4</errtype>
      <measure>1</measure>
      <measure_act>1</measure_act>
      <prob_cause>532</prob_cause>
     </test_error>
     <test_error>
      <nodeid>2000</nodeid>
      <errcod>1700290</errcod>
      <errpri>1</errpri>
      <errtype>4</errtype>
