=== miranvodnik/xdbd/system.tables.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="system.tables_root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="system.tables" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="table_id"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="table_name"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="128"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="table_type"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="128"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="schema_id"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="remarks"  minOccurs="0" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="128"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					<xs:key name="XPKsystem.tables">
						<xs:selector xpath=".//system.tables"/>
						<xs:field xpath="table_id"/>
					</xs:key>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== miranvodnik/xdbd/xdbd-xml/system.tables.xml
<?xml version="1.0" encoding="UTF-8"?>
<system.tables_root xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='system.tables.xsd'>
  <system.tables>
    <table_id>1</table_id>
    <table_name>basic_filter</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>basic_filter</remarks>
  </system.tables>
  <system.tables>
    <table_id>2</table_id>
    <table_name>cas_reg_param</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>cas_reg_param</remarks>
  </system.tables>
  <system.tables>
    <table_id>3</table_id>
    <table_name>coco_net_addr</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>coco_net_addr</remarks>
  </system.tables>
  <system.tables>
    <table_id>4</table_id>
    <table_name>disk_usage</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>disk_usage</remarks>
  </system.tables>
  <system.tables>
    <table_id>5</table_id>
    <table_name>error_filter</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>error_filter</remarks>
  </system.tables>
  <system.tables>
    <table_id>6</table_id>
    <table_name>error_priority</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>error_priority</remarks>
  </system.tables>
  <system.tables>
    <table_id>7</table_id>
    <table_name>eth_interface</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>eth_interface</remarks>
  </system.tables>
  <system.tables>
    <table_id>8</table_id>
    <table_name>ext_media_options</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>ext_media_options</remarks>
  </system.tables>
  <system.tables>
    <table_id>9</table_id>
    <table_name>filter</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>filter</remarks>
  </system.tables>
  <system.tables>
    <table_id>10</table_id>
    <table_name>filter_grp_member</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>filter_grp_member</remarks>
  </system.tables>
  <system.tables>
    <table_id>11</table_id>
    <table_name>gain_control_profile</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>gain_control_profile</remarks>
  </system.tables>
  <system.tables>
    <table_id>12</table_id>
    <table_name>h248_interface</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>h248_interface</remarks>
  </system.tables>
  <system.tables>
    <table_id>13</table_id>
    <table_name>h248_intf_profile</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>h248_intf_profile</remarks>
  </system.tables>
  <system.tables>
    <table_id>14</table_id>
    <table_name>h248_nonstd_prf</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>h248_nonstd_prf</remarks>
  </system.tables>
  <system.tables>
    <table_id>15</table_id>
    <table_name>h248_trace</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>h248_trace</remarks>
  </system.tables>
  <system.tables>
    <table_id>16</table_id>
    <table_name>ip_device</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>ip_device</remarks>
  </system.tables>
  <system.tables>
    <table_id>17</table_id>
    <table_name>ip_route</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>ip_route</remarks>
  </system.tables>
  <system.tables>
    <table_id>18</table_id>
    <table_name>media_opt_by_func</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>media_opt_by_func</remarks>
  </system.tables>
  <system.tables>
    <table_id>19</table_id>
    <table_name>media_options</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>media_options</remarks>
  </system.tables>
  <system.tables>
    <table_id>20</table_id>
    <table_name>mf_tone</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>mf_tone</remarks>
  </system.tables>
  <system.tables>
    <table_id>21</table_id>
    <table_name>mn_sys_interface</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>mn_sys_interface</remarks>
  </system.tables>
  <system.tables>
    <table_id>22</table_id>
    <table_name>node</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>node</remarks>
  </system.tables>
  <system.tables>
    <table_id>23</table_id>
    <table_name>node_config</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>node_config</remarks>
  </system.tables>
  <system.tables>
    <table_id>24</table_id>
    <table_name>protocol_qos</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>protocol_qos</remarks>
  </system.tables>
  <system.tables>
    <table_id>25</table_id>
    <table_name>reg_sig_level</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>reg_sig_level</remarks>
  </system.tables>
  <system.tables>
    <table_id>26</table_id>
    <table_name>rtp_control</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>rtp_control</remarks>
  </system.tables>
  <system.tables>
    <table_id>27</table_id>
    <table_name>rtp_limit</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>rtp_limit</remarks>
  </system.tables>
  <system.tables>
    <table_id>28</table_id>
    <table_name>rtp_quality</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>rtp_quality</remarks>
  </system.tables>
  <system.tables>
    <table_id>29</table_id>
    <table_name>statistics_group</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>statistics_group</remarks>
  </system.tables>
  <system.tables>
    <table_id>30</table_id>
    <table_name>sys_interface</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>sys_interface</remarks>
  </system.tables>
  <system.tables>
    <table_id>31</table_id>
    <table_name>syslog_client</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>syslog_client</remarks>
  </system.tables>
  <system.tables>
    <table_id>32</table_id>
    <table_name>test_error</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>test_error</remarks>
  </system.tables>
  <system.tables>
    <table_id>33</table_id>
    <table_name>test_program</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>test_program</remarks>
  </system.tables>
  <system.tables>
    <table_id>34</table_id>
    <table_name>tone</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>tone</remarks>
  </system.tables>
  <system.tables>
    <table_id>35</table_id>
    <table_name>tone_phase</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>tone_phase</remarks>
  </system.tables>
  <system.tables>
    <table_id>36</table_id>
    <table_name>tone_signal</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>tone_signal</remarks>
  </system.tables>
  <system.tables>
    <table_id>37</table_id>
    <table_name>vxml_config</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>vxml_config</remarks>
  </system.tables>
  <system.tables>
    <table_id>38</table_id>
    <table_name>vxml_server</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>vxml_server</remarks>
  </system.tables>
  <system.tables>
    <table_id>39</table_id>
    <table_name>vxml_trace</table_name>
    <table_type>BASE TABLE</table_type>
    <schema_id>1</schema_id>
    <remarks>vxml_trace</remarks>
  </system.tables>
</system.tables_root>
