=== miranvodnik/xdbd/tone.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="tone_root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="tone" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nodeid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="toneid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="tone_ctg"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="cn_treat"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="periods"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							</xs:sequence>
					</xs:complexType>
				</xs:element>
			<xs:element name="tone_phase" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nodeid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="toneid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="phaseid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="phaselen"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="intrptblty"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="tone_sigid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							</xs:sequence>
					</xs:complexType>
				</xs:element>
			<xs:element name="tone_signal" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nodeid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="tone_sigid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="frequency1"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="level1_db"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="frequency2"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="level2_db"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="XPKtone">
			<xs:selector xpath=".//tone"/>
			<xs:field xpath="nodeid"/>
			<xs:field xpath="toneid"/>
			</xs:key>
		<xs:key name="XPKtone_phase">
			<xs:selector xpath=".//tone_phase"/>
			<xs:field xpath="nodeid"/>
			<xs:field xpath="toneid"/>
			<xs:field xpath="phaseid"/>
			</xs:key>
		<xs:key name="XPKtone_signal">
			<xs:selector xpath=".//tone_signal"/>
			<xs:field xpath="nodeid"/>
			<xs:field xpath="tone_sigid"/>
			</xs:key>
		
		
		
		<xs:keyref name="XIF1tone_phase"  refer="XPKtone">
			<xs:selector xpath=".//tone_phase"/>
			<xs:field xpath="nodeid"/>
			<xs:field xpath="toneid"/>
			</xs:keyref>
		
	</xs:element>
</xs:schema>

=== miranvodnik/xdbd/xdbd-xml/tone.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<tone_root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='tone.xsd'>

     <tone>
      <nodeid>2000</nodeid>
      <toneid>10</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>2</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>11</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>2</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>12</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>2</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>13</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>2</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>14</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>1</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>15</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>0</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>16</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>0</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>17</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>1</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>18</toneid>
      <tone_ctg>2</tone_ctg>
      <cn_treat>1</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>19</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>0</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>20</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>1</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>21</toneid>
      <tone_ctg>2</tone_ctg>
      <cn_treat>0</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>22</toneid>
      <tone_ctg>3</tone_ctg>
      <cn_treat>0</cn_treat>
      <periods>1</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>23</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>1</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>24</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>0</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>25</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>0</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>26</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>1</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>27</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>2</cn_treat>
      <periods>1</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>28</toneid>
      <tone_ctg>3</tone_ctg>
      <cn_treat>0</cn_treat>
      <periods>1</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>29</toneid>
      <tone_ctg>3</tone_ctg>
      <cn_treat>0</cn_treat>
      <periods>1</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>30</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>0</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>31</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>2</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>33</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>0</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>34</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>2</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>35</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>1</cn_treat>
      <periods>255</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>36</toneid>
      <tone_ctg>3</tone_ctg>
      <cn_treat>0</cn_treat>
      <periods>1</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>37</toneid>
      <tone_ctg>3</tone_ctg>
      <cn_treat>0</cn_treat>
      <periods>1</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>38</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>0</cn_treat>
      <periods>8</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>39</toneid>
      <tone_ctg>2</tone_ctg>
      <cn_treat>1</cn_treat>
      <periods>1</periods>
     </tone>
     <tone>
      <nodeid>2000</nodeid>
      <toneid>40</toneid>
      <tone_ctg>1</tone_ctg>
      <cn_treat>0</cn_treat>
      <periods>1</periods>
     </tone>

     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>10</toneid>
      <phaseid>1</phaseid>
      <phaselen>5000</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>101</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>11</toneid>
      <phaseid>1</phaseid>
      <phaselen>400</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>101</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>11</toneid>
      <phaseid>2</phaseid>
      <phaselen>40</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>0</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>12</toneid>
      <phaseid>1</phaseid>
      <phaselen>1000</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>101</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>12</toneid>
      <phaseid>2</phaseid>
      <phaselen>4000</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>1</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>13</toneid>
      <phaseid>1</phaseid>
      <phaselen>350</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>101</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>13</toneid>
      <phaseid>2</phaseid>
      <phaselen>350</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>0</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>14</toneid>
      <phaseid>1</phaseid>
      <phaselen>175</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>101</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>14</toneid>
      <phaseid>2</phaseid>
      <phaselen>175</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>0</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>15</toneid>
      <phaseid>1</phaseid>
      <phaselen>330</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>102</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>15</toneid>
      <phaseid>2</phaseid>
      <phaselen>330</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>102</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>15</toneid>
      <phaseid>3</phaseid>
      <phaselen>330</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>104</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>15</toneid>
      <phaseid>4</phaseid>
      <phaselen>1000</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>0</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>16</toneid>
      <phaseid>1</phaseid>
      <phaselen>200</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>101</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>16</toneid>
      <phaseid>2</phaseid>
      <phaselen>5000</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>0</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>17</toneid>
      <phaseid>1</phaseid>
      <phaselen>200</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>101</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>17</toneid>
      <phaseid>2</phaseid>
      <phaselen>5000</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>0</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>18</toneid>
      <phaseid>1</phaseid>
      <phaselen>250</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>105</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>18</toneid>
      <phaseid>2</phaseid>
      <phaselen>250</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>0</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>18</toneid>
      <phaseid>3</phaseid>
      <phaselen>250</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>105</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>18</toneid>
      <phaseid>4</phaseid>
      <phaselen>1250</phaselen>
      <intrptblty>1</intrptblty>
      <tone_sigid>0</tone_sigid>
     </tone_phase>
     <tone_phase>
      <nodeid>2000</nodeid>
      <toneid>19</toneid>
      <phaseid>1</phaseid>
      <phaselen>5000</phaselen>
