=== miranvodnik/xdbd/xml-db/xsd-db/dtmf_gen.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="dtmf_gen_root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="cas_reg_param" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nodeid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="regsigtype"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="regsigvariant"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="cas_attenuation"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="wait_su"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="delay_before_end"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="pulse_length"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="pulse_long"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="pulse_secure"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="pause_length"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="pause_long"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="pause_secure"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="regsigparvalue1"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="regsigparvalue2"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="regsigparvalue3"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							</xs:sequence>
					</xs:complexType>
				</xs:element>
			<xs:element name="mf_tone" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nodeid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="mftoneid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="mf_frequency1"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="mf_frequency2"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							</xs:sequence>
					</xs:complexType>
				</xs:element>
			<xs:element name="reg_sig_level" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nodeid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="regsigtype"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="first_mf_level"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="scnd_mf_level"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="XPKcas_reg_param">
			<xs:selector xpath=".//cas_reg_param"/>
			<xs:field xpath="nodeid"/>
			<xs:field xpath="regsigtype"/>
			<xs:field xpath="regsigvariant"/>
			</xs:key>
		<xs:key name="XPKmf_tone">
			<xs:selector xpath=".//mf_tone"/>
			<xs:field xpath="nodeid"/>
			<xs:field xpath="mftoneid"/>
			</xs:key>
		<xs:key name="XPKreg_sig_level">
			<xs:selector xpath=".//reg_sig_level"/>
			<xs:field xpath="nodeid"/>
			<xs:field xpath="regsigtype"/>
			</xs:key>
		
		
		
		</xs:element>
</xs:schema>

=== miranvodnik/xdbd/xml-db/xml-db-old/dtmf_gen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<dtmf_gen_root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='dtmf_gen.xsd'>

     <cas_reg_param>
      <nodeid>2000</nodeid>
      <regsigtype>8</regsigtype>
      <regsigvariant>0</regsigvariant>
      <cas_attenuation>0</cas_attenuation>
      <wait_su>5</wait_su>
      <delay_before_end>20</delay_before_end>
      <pulse_length>70</pulse_length>
      <pulse_long>0</pulse_long>
      <pulse_secure>0</pulse_secure>
      <pause_length>70</pause_length>
      <pause_long>0</pause_long>
      <pause_secure>0</pause_secure>
      <regsigparvalue1>30</regsigparvalue1>
      <regsigparvalue2>700</regsigparvalue2>
      <regsigparvalue3>0</regsigparvalue3>
     </cas_reg_param>

     <mf_tone>
      <nodeid>2000</nodeid>
      <mftoneid>17</mftoneid>
      <mf_frequency1>941</mf_frequency1>
      <mf_frequency2>1336</mf_frequency2>
     </mf_tone>
      <mf_tone>
      <nodeid>2000</nodeid>
      <mftoneid>18</mftoneid>
      <mf_frequency1>697</mf_frequency1>
      <mf_frequency2>1209</mf_frequency2>
     </mf_tone>
      <mf_tone>
      <nodeid>2000</nodeid>
      <mftoneid>19</mftoneid>
      <mf_frequency1>697</mf_frequency1>
      <mf_frequency2>1336</mf_frequency2>
     </mf_tone>
      <mf_tone>
      <nodeid>2000</nodeid>
      <mftoneid>20</mftoneid>
      <mf_frequency1>697</mf_frequency1>
      <mf_frequency2>1477</mf_frequency2>
     </mf_tone>
      <mf_tone>
      <nodeid>2000</nodeid>
      <mftoneid>21</mftoneid>
      <mf_frequency1>770</mf_frequency1>
      <mf_frequency2>1209</mf_frequency2>
     </mf_tone>
      <mf_tone>
      <nodeid>2000</nodeid>
      <mftoneid>22</mftoneid>
      <mf_frequency1>770</mf_frequency1>
      <mf_frequency2>1336</mf_frequency2>
     </mf_tone>
      <mf_tone>
      <nodeid>2000</nodeid>
      <mftoneid>23</mftoneid>
      <mf_frequency1>770</mf_frequency1>
      <mf_frequency2>1477</mf_frequency2>
     </mf_tone>
      <mf_tone>
      <nodeid>2000</nodeid>
      <mftoneid>24</mftoneid>
      <mf_frequency1>852</mf_frequency1>
      <mf_frequency2>1209</mf_frequency2>
     </mf_tone>
      <mf_tone>
      <nodeid>2000</nodeid>
      <mftoneid>25</mftoneid>
      <mf_frequency1>582</mf_frequency1>
      <mf_frequency2>1336</mf_frequency2>
     </mf_tone>
      <mf_tone>
      <nodeid>2000</nodeid>
      <mftoneid>26</mftoneid>
      <mf_frequency1>852</mf_frequency1>
      <mf_frequency2>1477</mf_frequency2>
     </mf_tone>
      <mf_tone>
      <nodeid>2000</nodeid>
      <mftoneid>27</mftoneid>
      <mf_frequency1>697</mf_frequency1>
      <mf_frequency2>1633</mf_frequency2>
     </mf_tone>
      <mf_tone>
      <nodeid>2000</nodeid>
      <mftoneid>28</mftoneid>
      <mf_frequency1>770</mf_frequency1>
      <mf_frequency2>1633</mf_frequency2>
     </mf_tone>
      <mf_tone>
      <nodeid>2000</nodeid>
      <mftoneid>29</mftoneid>
      <mf_frequency1>852</mf_frequency1>
      <mf_frequency2>1633</mf_frequency2>
     </mf_tone>
      <mf_tone>
      <nodeid>2000</nodeid>
      <mftoneid>30</mftoneid>
      <mf_frequency1>941</mf_frequency1>
      <mf_frequency2>1633</mf_frequency2>
     </mf_tone>
      <mf_tone>
      <nodeid>2000</nodeid>
      <mftoneid>31</mftoneid>
      <mf_frequency1>941</mf_frequency1>
      <mf_frequency2>1209</mf_frequency2>
     </mf_tone>
      <mf_tone>
      <nodeid>2000</nodeid>
      <mftoneid>32</mftoneid>
      <mf_frequency1>941</mf_frequency1>
      <mf_frequency2>1477</mf_frequency2>
     </mf_tone>

     <reg_sig_level>
      <nodeid>2000</nodeid>
      <regsigtype>8</regsigtype>
      <first_mf_level>-100</first_mf_level>
      <scnd_mf_level>-80</scnd_mf_level>
     </reg_sig_level>

</dtmf_gen_root>
