=== miranvodnik/xdbd/xml-db/xsd-db/ms_options.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ms_options_root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ext_media_options" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nodeid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="fax_rate_maneg"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="fax_max_bit_rate" default="14400" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="fax_udp_ec" default="1" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="fax_fill_bit_rem" default="0" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="fax_trans_jbig" default="0" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="fax_trans_mmr" default="0" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="fax_version" default="0" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="fax_max_buffer" default="800" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="fax_max_datagram" default="189" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="dtmf_fr_spread" default="2" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="dtmf_dtct_time" default="30" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="rx_alc" default="0" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short">
											<xs:minInclusive value="-128"/>
											<xs:maxInclusive value="127"/>
										</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="silence_supp_tresh" default="0" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short">
											<xs:minInclusive value="-128"/>
											<xs:maxInclusive value="127"/>
										</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="faxmod_tone_relay"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="faxmod_tone_txplt"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="faxmod_tone_rxplt"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							</xs:sequence>
					</xs:complexType>
				</xs:element>
			<xs:element name="media_opt_by_func" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nodeid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="media_opt_func_id"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="media_opt_func_name"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:string">
											<xs:minLength value="0"/>
											<xs:maxLength value="50"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="vad_threshold" default="-24" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short">
											<xs:minInclusive value="-128"/>
											<xs:maxInclusive value="127"/>
										</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="time_dtct_silence"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="time_dtct_talk" default="0" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="media_opt_reserve1" default="0" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="media_opt_reserve2" default="0" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="media_opt_reserve3" default="0" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							</xs:sequence>
					</xs:complexType>
				</xs:element>
			<xs:element name="node" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nodeid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="statistics_period" default="15" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="h248text_encodtype" default="1" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="h248_version" default="1" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="sorm_alarm_info" default="1" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="XPKext_media_optio">
			<xs:selector xpath=".//ext_media_options"/>
			<xs:field xpath="nodeid"/>
			<xs:field xpath="fax_rate_maneg"/>
			</xs:key>
		<xs:key name="XPKmedia_opt_by_fu">
			<xs:selector xpath=".//media_opt_by_func"/>
			<xs:field xpath="nodeid"/>
			<xs:field xpath="media_opt_func_id"/>
			</xs:key>
		<xs:key name="XPKnode">
			<xs:selector xpath=".//node"/>
			<xs:field xpath="nodeid"/>
			</xs:key>
		
		<xs:unique name="XAK1media_opt_by_f">
			<xs:selector xpath=".//media_opt_by_func"/>
			<xs:field xpath="nodeid"/>
			<xs:field xpath="media_opt_func_name"/>
			</xs:unique>
		
		</xs:element>
</xs:schema>

=== miranvodnik/xdbd/xml-db/xml-db/ms_options.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<ms_options_root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='ms_options.xsd'>

    <ext_media_options>
	<nodeid>2000</nodeid>
	<fax_rate_maneg>1</fax_rate_maneg>
	<fax_max_bit_rate>14400</fax_max_bit_rate>
	<fax_udp_ec>1</fax_udp_ec>
	<fax_fill_bit_rem>0</fax_fill_bit_rem>
	<fax_trans_jbig>0</fax_trans_jbig>
	<fax_trans_mmr>0</fax_trans_mmr>
	<fax_version>0</fax_version>
	<fax_max_buffer>800</fax_max_buffer>
	<fax_max_datagram>189</fax_max_datagram>
	<dtmf_fr_spread>2</dtmf_fr_spread>
	<dtmf_dtct_time>30</dtmf_dtct_time>
	<rx_alc>0</rx_alc>
	<silence_supp_tresh>0</silence_supp_tresh>
	<faxmod_tone_relay>0</faxmod_tone_relay>
	<faxmod_tone_txplt>101</faxmod_tone_txplt>
	<faxmod_tone_rxplt>101</faxmod_tone_rxplt>
    </ext_media_options>

    <media_opt_by_func>
	<nodeid>2000</nodeid>
	<media_opt_func_id>0</media_opt_func_id>
	<media_opt_func_name>Media Server</media_opt_func_name>
	<vad_threshold>-24</vad_threshold>
	<time_dtct_silence>500</time_dtct_silence>
	<time_dtct_talk>0</time_dtct_talk>
	<media_opt_reserve1>0</media_opt_reserve1>
	<media_opt_reserve2>0</media_opt_reserve2>
	<media_opt_reserve3>0</media_opt_reserve3>
    </media_opt_by_func>
    <media_opt_by_func>
	<nodeid>2000</nodeid>
	<media_opt_func_id>1</media_opt_func_id>
	<media_opt_func_name>Proxy Media Server</media_opt_func_name>
	<vad_threshold>-30</vad_threshold>
	<time_dtct_silence>200</time_dtct_silence>
	<time_dtct_talk>0</time_dtct_talk>
	<media_opt_reserve1>0</media_opt_reserve1>
	<media_opt_reserve2>0</media_opt_reserve2>
	<media_opt_reserve3>0</media_opt_reserve3>
    </media_opt_by_func>

    <node>
	<nodeid>2000</nodeid>
	<statistics_period>15</statistics_period>
	<h248text_encodtype>1</h248text_encodtype>
	<h248_version>1</h248_version>
	<sorm_alarm_info>1</sorm_alarm_info>
    </node>

</ms_options_root>
