=== miranvodnik/xdbd/db/dynamic.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="dynamic_root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="h248_trace" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nodeid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="sys_intf_id"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="sigtrace_req"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							</xs:sequence>
					</xs:complexType>
				</xs:element>
			<xs:element name="vxml_trace" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nodeid"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="vxml_module"  minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="vxml_tracemask" default="0" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="vxml_debugmask" default="0" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base = "xs:short"/>
								</xs:simpleType>
							</xs:element>
							</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="XPKh248_trace">
			<xs:selector xpath=".//h248_trace"/>
			<xs:field xpath="nodeid"/>
			<xs:field xpath="sys_intf_id"/>
			</xs:key>
		<xs:key name="XPKvxml_trace">
			<xs:selector xpath=".//vxml_trace"/>
			<xs:field xpath="nodeid"/>
			<xs:field xpath="vxml_module"/>
			</xs:key>
		
		
		</xs:element>
</xs:schema>

=== miranvodnik/xdbd/xdbd-xml/dynamic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<dynamic_root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='dynamic.xsd'>

    <vxml_trace>
      <nodeid>2000</nodeid>
      <vxml_module>1</vxml_module>
      <vxml_tracemask>0</vxml_tracemask>
      <vxml_debugmask>0</vxml_debugmask>
     </vxml_trace>
     <vxml_trace>
      <nodeid>2000</nodeid>
      <vxml_module>2</vxml_module>
      <vxml_tracemask>0</vxml_tracemask>
      <vxml_debugmask>0</vxml_debugmask>
     </vxml_trace>
     <vxml_trace>
      <nodeid>2000</nodeid>
      <vxml_module>3</vxml_module>
      <vxml_tracemask>0</vxml_tracemask>
      <vxml_debugmask>0</vxml_debugmask>
     </vxml_trace>
     <vxml_trace>
      <nodeid>2000</nodeid>
      <vxml_module>4</vxml_module>
      <vxml_tracemask>0</vxml_tracemask>
      <vxml_debugmask>0</vxml_debugmask>
     </vxml_trace>
     <vxml_trace>
      <nodeid>2000</nodeid>
      <vxml_module>5</vxml_module>
      <vxml_tracemask>0</vxml_tracemask>
      <vxml_debugmask>0</vxml_debugmask>
     </vxml_trace>
     <vxml_trace>
      <nodeid>2000</nodeid>
      <vxml_module>6</vxml_module>
      <vxml_tracemask>0</vxml_tracemask>
      <vxml_debugmask>0</vxml_debugmask>
     </vxml_trace>
     <vxml_trace>
      <nodeid>2000</nodeid>
      <vxml_module>7</vxml_module>
      <vxml_tracemask>0</vxml_tracemask>
      <vxml_debugmask>0</vxml_debugmask>
     </vxml_trace>
     <vxml_trace>
      <nodeid>2000</nodeid>
      <vxml_module>8</vxml_module>
      <vxml_tracemask>0</vxml_tracemask>
      <vxml_debugmask>0</vxml_debugmask>
     </vxml_trace>
     <vxml_trace>
      <nodeid>2000</nodeid>
      <vxml_module>9</vxml_module>
      <vxml_tracemask>0</vxml_tracemask>
      <vxml_debugmask>0</vxml_debugmask>
     </vxml_trace>
     <vxml_trace>
      <nodeid>2000</nodeid>
      <vxml_module>10</vxml_module>
      <vxml_tracemask>0</vxml_tracemask>
      <vxml_debugmask>0</vxml_debugmask>
     </vxml_trace>
     <vxml_trace>
      <nodeid>2000</nodeid>
      <vxml_module>11</vxml_module>
      <vxml_tracemask>0</vxml_tracemask>
      <vxml_debugmask>0</vxml_debugmask>
     </vxml_trace>
     <vxml_trace>
      <nodeid>2000</nodeid>
      <vxml_module>12</vxml_module>
      <vxml_tracemask>0</vxml_tracemask>
      <vxml_debugmask>0</vxml_debugmask>
     </vxml_trace>
     <vxml_trace>
      <nodeid>2000</nodeid>
      <vxml_module>13</vxml_module>
      <vxml_tracemask>0</vxml_tracemask>
      <vxml_debugmask>0</vxml_debugmask>
     </vxml_trace>
     <vxml_trace>
      <nodeid>2000</nodeid>
      <vxml_module>14</vxml_module>
      <vxml_tracemask>0</vxml_tracemask>
      <vxml_debugmask>0</vxml_debugmask>
     </vxml_trace>
     <vxml_trace>
      <nodeid>2000</nodeid>
      <vxml_module>15</vxml_module>
      <vxml_tracemask>0</vxml_tracemask>
      <vxml_debugmask>0</vxml_debugmask>
     </vxml_trace>

</dynamic_root>
